from enum import Enum

class Events(Enum):
	DISCONNECT = 0
	REQ_ACC_LOGIN = 1
	REQ_ACC_CREATE = 2
	REQ_ADD_FRIEND = 3
	REQ_SEND_UPDATES = 4
	REQ_START_CHAT = 5
	REQ_CHAT_INV_ACCEPT = 6
	REQ_CHAT_INV_REJECT = 7
	SEND_MESSAGE = 10
	
	# DH events
	DH_PUBLIC_SHARE = 101
	DH_PUBLIC_ACK = 102
	DH_KEY_SHARE = 103
	DH_KEY_ACK_SHARE = 104
	DH_ACK = 105

	# client events
	EVT_NEW_MESSAGE = 201
	EVT_NEW_REQUEST = 202

